version: "3.9"
services:
  db: # https://medium.com/better-programming/persistent-databases-using-dockers-volumes-and-mongodb-9ac284c25b39
    image: mongo:latest # https://hub.docker.com/_/mongo/
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - "~/mongo/data:/data/db"
  server:
    image: "samhuckaby/server.forpreaching.com"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: server
    environment:
      DB_HOST: 172.26.15.49
      DB_PORT: 27017
      NODE_ENV: 'prod'
      REPO_USER: "INSERT USER HERE"
      REPO_PASS: "INSERT PASSWORD HERE"
      VIRTUAL_HOST: "server.forpreaching.com"
      LETSENCRYPT_HOST: "server.forpreaching.com"
  illustrations:
    image: "samhuckaby/forpreaching.com"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: illustrations
    environment:
      REPO_USER: "INSERT USER HERE"
      REPO_PASS: "INSERT PASSWORD HERE"
      VIRTUAL_HOST: "illustrations.forpreaching.com"
      LETSENCRYPT_HOST: "illustrations.forpreaching.com"
  sermons:
    image: "samhuckaby/sermons.forpreaching.com"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: sermons
    environment:
      REPO_USER: "INSERT USER HERE"
      REPO_PASS: "INSERT PASSWORD HERE"
      VIRTUAL_HOST: "sermons.forpreaching.com"
      LETSENCRYPT_HOST: "sermons.forpreaching.com"
  watchtower: 
    # https://chriswiegman.com/2019/12/keeping-docker-containers-updated/
    # https://containrrr.dev/watchtower/usage-overview/
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    environment:
      REPO_USER: "INSERT USER HERE"
      REPO_PASS: "INSERT PASSWORD HERE"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# https://github.com/nginx-proxy/nginx-proxy/issues/1132
# On the AWS instance, you must first run:
  # `docker network create webproxy`
# You must also start the nginx-proxy and the letsencrypt-nginx-proxy-companion with the --network flag set to `webproxy`
networks:
  default:
    external:
      name: webproxy